# Generated by Django 6.0.7 on 2026-07-30 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('affiliation', models.CharField(default='Addis Ababa Science and Technology University (AASTU)', max_length=255)),
                ('college', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('applied_science', 'Applied Science')], max_length=50)),
                ('center_of_excellence', models.CharField(blank=True, choices=[], max_length=50)),
                ('department', models.CharField(max_length=255)),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('researcher', 'Researcher'), ('lecturer', 'Lecturer'), ('professor', 'Professor'), ('assistant_lecturer', 'Assistant Lecturer'), ('data_scientist', 'Data Scientist'), ('software_engineer', 'Software Engineer'), ('government_officer', 'Government Officer'), ('industry_professional', 'Industry Professional'), ('other', 'Other')], max_length=30)),
                ('academic_title', models.CharField(blank=True, choices=[('none', 'None'), ('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('eng', 'Eng.'), ('dr', 'Dr.'), ('prof', 'Prof.')], default='none', max_length=10)),
                ('highest_degree', models.CharField(blank=True, choices=[('high_school', 'High School Diploma'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('postdoc', 'Postdoctoral Fellowship'), ('other', 'Other')], max_length=20)),
                ('orcid_id', models.CharField(blank=True, max_length=19)),
                ('research_interests', models.JSONField(default=list)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('additional_link', models.URLField(blank=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Everyone (Public)'), ('trusted', 'Trusted Parties'), ('private', 'Only Me (Private)')], default='private', max_length=10)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
