# Generated by Django 6.0.7 on 2026-08-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('public', 'Public'), ('researcher', 'Researcher'), ('checker', 'Checker/Reviewer'), ('admin', 'Admin')], default='researcher', max_length=20),
        ),
    ]
