# Generated by Django 6.0.7 on 2026-08-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='occupation',
            new_name='academia',
        ),
    ]
