# Generated by Django 6.0.7 on 2026-08-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_occupation_to_academia'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to='metadata.category'),
        ),
    ]
