# Generated by Django 6.0.7 on 2026-08-02 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
    ("accounts", "0009b_null_empty_college_coe_department"),  
]

    operations = [
        migrations.CreateModel(
            name='CenterOfExcellence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_rank',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('graduate_assistant', 'Graduate Assistant'), ('assistant_lecturer', 'Assistant Lecturer'), ('lecturer', 'Lecturer'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor')], default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='center_of_excellence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.centerofexcellence'),
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE accounts_userprofile ALTER COLUMN center_of_excellence DROP NOT NULL;",
                "ALTER TABLE accounts_userprofile ALTER COLUMN college DROP NOT NULL;",
                "ALTER TABLE accounts_userprofile ALTER COLUMN department DROP NOT NULL;",
                "UPDATE accounts_userprofile SET center_of_excellence = NULL WHERE center_of_excellence = '';",
                "UPDATE accounts_userprofile SET college = NULL WHERE college = '';",
                "UPDATE accounts_userprofile SET department = NULL WHERE department = '';",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.college'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('center_of_excellence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.centerofexcellence')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.college')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('center_of_excellence__isnull', True), ('college__isnull', False)), models.Q(('center_of_excellence__isnull', False), ('college__isnull', True)), _connector='OR'), name='department_belongs_to_college_xor_coe'),
        ),
    ]
