# Generated by Django 6.0.7 on 2026-08-09 10:48

import django.db.models.deletion
from django.db import migrations, models

def backfill_roles(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserRole = apps.get_model("accounts", "UserRole")
    UserRole.objects.bulk_create(
        [UserRole(profile=p, role=p.role) for p in UserProfile.objects.all()],
        ignore_conflicts=True,
    )
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_centerofexcellence_college_userprofile_academic_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('public', 'Public'), ('researcher', 'Researcher'), ('checker', 'Checker'), ('admin', 'Admin')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'role')},
            },
        ),
    ]
