# Generated by Django 6.0.7 on 2026-08-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_email_verified_and_more'),
        ('accounts', '0011_userrole'),
    ]

    operations = [
    ]
