# Generated by Django 6.0.7 on 2026-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260815_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
