# Generated by Django 6.0.7 on 2026-08-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_emailverificationtoken_passwordresettoken'),
        ('metadata', '0008_metadata_collaborators_text_metadata_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherrequest',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='researcherrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='academia',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('researcher', 'Researcher'), ('lecturer', 'Lecturer'), ('professor', 'Professor'), ('assistant_lecturer', 'Assistant Lecturer'), ('data_scientist', 'Data Scientist'), ('software_engineer', 'Software Engineer'), ('government_officer', 'Government Officer'), ('industry_professional', 'Industry Professional'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='users_with_expertise', to='metadata.category'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='research_interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='metadata.category'),
        ),
        migrations.DeleteModel(
            name='ResearchCategory',
        ),
        migrations.DeleteModel(
            name='ResearcherRequest',
        ),
    ]
