# Generated by Django 6.0.7 on 2026-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_researcherrequest_decided_by_and_more'),
        ('metadata', '0008_metadata_collaborators_text_metadata_coverage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='research_interests_completed',
            new_name='interests_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='research_interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users_with_interests', to='metadata.category'),
        ),
    ]
