# Generated by Django 6.0.7 on 2026-08-27 15:54

from django.db import migrations, models


def rename_checker_to_reviewer(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserRole = apps.get_model("accounts", "UserRole")

    UserProfile.objects.filter(role="checker").update(role="reviewer")
    UserRole.objects.filter(role="checker").update(role="reviewer")


def rename_reviewer_to_checker(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserRole = apps.get_model("accounts", "UserRole")

    UserProfile.objects.filter(role="reviewer").update(role="checker")
    UserRole.objects.filter(role="reviewer").update(role="checker")


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0017_rename_research_interests_completed_userprofile_interests_completed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("researcher", "Researcher"),
                    ("reviewer", "Reviewer"),
                    ("admin", "Admin"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("researcher", "Researcher"),
                    ("reviewer", "Reviewer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(
            rename_checker_to_reviewer,
            rename_reviewer_to_checker,
        ),
    ]