# Generated by Django 6.0.7 on 2026-08-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_userprofile_role_alter_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academia_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highest_degree_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
