# Generated by Django 6.0.7 on 2026-08-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_profile_completed_userprofile_can_upload_datasets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upload_permission_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Everyone (Public)'), ('private', 'Only Me (Private)')], default='private', max_length=10),
        ),
    ]
