# Generated by Django 6.0.7 on 2026-08-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userrole_is_primary'),
        ('accounts', '0022_userprofile_upload_permission_revoked_and_more'),
    ]

    operations = [
    ]
