# Generated by Django 6.0.7 on 2026-09-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20260829_0811'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='department_belongs_to_college_xor_coe',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
