# Generated by Django 6.0.7 on 2026-09-03 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_department_department_belongs_to_college_xor_coe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('email', 'Email'), ('password_hash', 'Password hash')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['credential_type', 'value'], name='accounts_bl_credent_71b1cb_idx')],
            },
        ),
    ]
