# Generated by Django 6.0.7 on 2026-09-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userprofile_must_change_password'),
        ('accounts', '0025_blockedcredential'),
    ]

    operations = [
    ]
