# Generated by Django 6.0.7 on 2026-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_backfill_missing_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedcredential',
            name='credential_type',
            field=models.CharField(choices=[('email', 'Email'), ('username', 'Username'), ('password_hash', 'Password hash')], max_length=20),
        ),
    ]
