# Generated by Copilot to add metadata search indexes

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_metadatahistory'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='metadata',
            index=GinIndex(fields=['description'], opclasses=['gin_trgm_ops'], name='metadata_description_trgm_gin'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=GinIndex(fields=['sponsor_or_grant'], opclasses=['gin_trgm_ops'], name='metadata_sponsor_trgm_gin'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(fields=['category', 'subject'], name='metadata_category_subject_idx'),
        ),
    ]
