# Generated by Django 6.0.7 on 2026-08-09 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_metadata_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackThumbnail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_key', models.CharField(max_length=512)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['usage_count'],
            },
        ),
        migrations.RemoveField(
            model_name='metadatahistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='metadatahistory',
            name='metadata',
        ),
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_description_trgm_gin',
        ),
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_sponsor_trgm_gin',
        ),
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_category_subject_idx',
        ),
        migrations.AddField(
            model_name='fallbackthumbnail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_thumbnails', to='metadata.category'),
        ),
        migrations.DeleteModel(
            name='MetadataHistory',
        ),
    ]
