# Generated by Django 6.0.7 on 2026-08-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_datasetcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='collaborators_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='coverage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='doi_citation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
