# Generated by Django 6.0.7 on 2026-08-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_metadata_collaborators_text_metadata_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
