# Generated by Django 6.0.7 on 2026-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_remove_metadata_subject_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='citation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='collection_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='data_preprocessing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='geographic_coverage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='metadata',
            name='has_header',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='has_missing_values',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='instances_represent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='recommended_data_splits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='related_resources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='sensitive_data_disclosure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='temporal_coverage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
