# Generated by Django 6.0.7 on 2026-08-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_metadata_citation_notes_metadata_collection_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='coverage',
        ),
    ]
