# Generated by Django 6.0.7 on 2026-08-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_remove_metadata_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='characteristics',
            field=models.ManyToManyField(blank=True, related_name='metadata', to='metadata.datasetcharacteristic'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='metadata', to='metadata.language'),
        ),
    ]
