# Generated by Django 6.0.7 on 2026-09-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_seed_standard_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='origin',
            field=models.CharField(choices=[('standard', 'Standard'), ('dataset_other', 'Dataset Other'), ('interest_other', 'Interest Other')], default='standard', max_length=20),
        ),
    ]
