# Generated by Django 6.0.7 on 2026-08-09 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('datasets', '0006_dataset_thumbnail_key_dataset_thumbnail_source'),
        ('metadata', '0004_fallbackthumbnail_remove_metadatahistory_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_suggestions', to='datasets.dataset')),
                ('fallback_thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.fallbackthumbnail')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dataset', 'reviewer')},
            },
        ),
    ]
