# Generated by Django 6.0.7 on 2026-08-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_datasetdeletionrequest_dataset_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationdecision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], max_length=18),
        ),
    ]
