# Generated by Django 6.0.7 on 2026-09-08 00:00

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_datasetreviewerassignment'),
        ('datasets', '0023_dataset_is_archived_dataset_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetArchiveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_title', models.CharField(blank=True, max_length=255)),
                ('reason_category', models.CharField(choices=[('outdated', 'Outdated'), ('duplicate', 'Duplicate'), ('privacy_or_sensitive', 'Privacy or Sensitive Data'), ('low_quality', 'Low Quality'), ('superseded', 'Superseded by a Newer Dataset'), ('no_longer_relevant', 'No Longer Relevant'), ('other', 'Other')], max_length=32)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_requests', to='datasets.dataset')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveRequestVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('archive_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='admin_panel.datasetarchiverequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('archive_request', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='DatasetUnarchiveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_title', models.CharField(blank=True, max_length=255)),
                ('intended_use', models.CharField(choices=[('research', 'Research'), ('teaching', 'Teaching'), ('reproducing_results', 'Reproducing Results'), ('personal_reference', 'Personal Reference'), ('other', 'Other')], max_length=32)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unarchive_requests', to='datasets.dataset')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]