# Generated by Django 6.0.7 on 2026-08-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_datasetaccessrequest_owner_decision_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharepermission',
            unique_together=set(),
        ),
    ]
