# Generated by Django 6.0.7 on 2026-08-01 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('upload_success', 'Upload Success'), ('upload_failure', 'Upload Failure'), ('new_version_available', 'New Version Available'), ('dataset_approved', 'Dataset Approved'), ('dataset_rejected', 'Dataset Rejected'), ('revision_proposed', 'Revision Proposed'), ('revision_rejected', 'Revision Rejected'), ('content_update_pending', 'Content Update Pending'), ('researcher_request', 'Researcher Request'), ('contributor_invitation', 'Contributor Invitation'), ('access_request', 'Access Request')], max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('link_path', models.CharField(blank=True, max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
