# Generated by Django 6.0.7 on 2026-08-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('upload_success', 'Upload Success'), ('upload_failure', 'Upload Failure'), ('new_version_available', 'New Version Available'), ('dataset_approved', 'Dataset Approved'), ('dataset_rejected', 'Dataset Rejected'), ('revision_proposed', 'Revision Proposed'), ('revision_rejected', 'Revision Rejected'), ('content_update_pending', 'Content Update Pending'), ('researcher_request', 'Researcher Request'), ('contributor_invitation', 'Contributor Invitation'), ('access_request', 'Access Request'), ('researcher_approved', 'Researcher Approved'), ('researcher_rejected', 'Researcher Rejected'), ('changes_requested', 'Changes Requested')], max_length=32),
        ),
    ]
